<a href="https://colab.research.google.com/github/RebuildYY/2016_1-_project2_snakegame/blob/master/p4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

def max(a, b, c, d):
  max = a
  if max < b:
    max = b
  if max < c:
    max = c
  if max < d:
    max = d
  return max


n = int(input())
if n % 2 != 0:
  print("짝수를 입력해주세요.")

else:
  A = np.random.random((n,n))
  B = np.zeros((int(n/2), int(n/2)))
  for i in range(0, n):
    for j in range(0, n):
      A[i][j] = round(A[i][j], 2)
  
  for i in range(0, n, 2):
    for j in range(0, n, 2):
      B[int(i/2)][int(j/2)] = max(A[i][j], A[i][j+1], A[i+1][j], A[i+1][j+1])
  
  print(A)
  print(B)

4
[[0.7  0.42 0.42 0.77]
 [0.18 0.05 0.99 0.26]
 [0.42 0.48 0.7  0.91]
 [0.04 0.58 0.89 0.88]]
[[0.7  0.99]
 [0.58 0.91]]
